// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sahti-dashboards/AdminDashboard.tsx": () => import("../components/mockups/sahti-dashboards/AdminDashboard.tsx"),
  "./components/mockups/sahti-dashboards/DesignSystem.tsx": () => import("../components/mockups/sahti-dashboards/DesignSystem.tsx"),
  "./components/mockups/sahti-dashboards/DoctorDashboard.tsx": () => import("../components/mockups/sahti-dashboards/DoctorDashboard.tsx"),
  "./components/mockups/sahti-dashboards/PatientDashboard.tsx": () => import("../components/mockups/sahti-dashboards/PatientDashboard.tsx")
};
